// Auto-generated from game_config.json
export const GameConfig = {
    gravityConstant: 300,
    gravityRadiusScale: 3,
    thrustPower: 300,
    minPlanetRadius: 15,
    maxPlanetRadius: 50,
    minPlanetsPerChunk: 2,
    maxPlanetsPerChunk: 5,
    chunkSize: 600,
    shipCollisionRadius: 5,
    fuelSpawnInterval: 10000,
    engineType: 2,
    musicType: 2,
    engineVolume: 0.3,
    musicVolume: 2.5,
    starFuelBurnRate: 20,
    nearMissSpeedThreshold: 200,
    nearMissFuelReward: 20,
    nearMissCooldown: 1,
};
